### ISSUE TITLE
multiple engines dont multiply data

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#101]
if a craft has 1 engine, or 3 (same part), it gains data at the same rate
each part should add its own data gains to the pool

**Comment by jwvanderbeck** [comment]
Hmm it certainly used to.

**Comment by anxcon** [comment]
been a few complaints in IRC so i tested, what brought this up.

took 1x of the solid rocket boosters "hammer" (3 sizes, its the medium)
had a launch, data went from 5000 to 6000 during the use on it
took 4x, repeat, data went 6000 to 7000 on all 4, rather than to 10000
another test with 3, burned center 1/2 as long, went to 8000
so its using the max gain, not combined gain

**Comment by jwvanderbeck** [comment]
I've looked at the code and it absolutely looks correct.  I will try to remember to check this in game.

**Comment by anxcon** [comment]
retested steps above to be sure still issue, test done under stock+TF

not sure how to fix it though ;\

**Comment by jwvanderbeck** [comment]
I tink I might know what is going on but it a bit tricky to unwind the stack so I need to get drunk and look at it :)

**Comment by jwvanderbeck** [comment]
Not quite fixed.  Some knock issues coming from the change.

**Comment by jwvanderbeck** [comment]
Actually I think this is all good.  The display shouldn't change because the extra data isn't applied to the current flight, and the other issue I saw was actually not a bug but the intended behavior.

So yeah I think this is good to go.
