### ISSUE TITLE
ModuleTestSubject effecting flight data gains?

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#104]
just thought id throw this out for thoughts and opinions and dreams

you're getting a contract to test parts, "under conditions", feels like part flight data should be influenced here, so far testflight basicly ignores conditions - an engine could be made to work for space, yet flight data fully gathered semi idle on launch pad, not exactly getting any data really ment for the part - that said a simple recorder for per environment could solve that bit unrelated to MTS

should parts unlocked by MTS only gather data if within MTS constraint zones?

**Comment by jwvanderbeck** [comment]
As for the first part of this, TF used to have such a setup where data and reliability was tracked per domain such as low altitude, high altitude, space, lunar, martian, etc but it was deemed too complex for the gameplay it provided.
