### ISSUE TITLE
TestFlight failures are FPS dependent (I think)

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/TestFlight#108]
Unless I am very much mistaken, code that runs during Update() runs once per (visual) frame. That means that failure checks run at a rate of (your visual FPS). That means that the faster your framerate, the more likely your part is to have a successful failure roll (because one is done per frame).

deltaTime needs to be figured in somehow.

**Comment by NathanKell** [comment]
Closed for being a big doody-head by looking in the wrong places. Thanks @anxcon.

**Comment by jwvanderbeck** [comment]
Everything is MET based so shouldn't be an issue unless I goofed somewhere.

**Comment by NathanKell** [comment]
Yeah, you didn't. I did. :D
