### ISSUE TITLE
What is "deepSpaceThreshold"? 

### ISSUE THREAD

**Issue by Scarab24** [KSP-RO/TestFlight#110]
Want to make some configuration for  parts in RO+RP-0
What is "deepSpaceThreshold"?

**Comment by jwvanderbeck** [comment]
What it is is completely irrelevant now:)  In the past it defined at what point you moved from being considered in space around a planet to being in "deep space". Now that we have removed the concept of "scopes" this setting does nothing. We should remove it from the code if it is still there. 

Sent from Outlook Mobile




On Thu, Feb 18, 2016 at 11:45 AM -0800, "Scarab24" <notifications@github.com> wrote:












Want to make some configuration for  parts in RO+RP-0

What is "deepSpaceThreshold"?
