### ISSUE TITLE
Update() vs FixedUpdate()

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#111]
@jwvanderbeck never did get an official answer as to the why - testflight uses Update() (gfx frame update) everywhere not FixedUpdate() (physics update), and while you did add some calculations to get accual time (and thus no real functional issue), i keep getting messaged by people freaking out over it and telling me its going to be lag based failure rates until i point out the timechecks lol

you had our poor beloved @NathanKell all worried for a bit too XD

**Comment by NathanKell** [comment]
It's a good policy, actually--physics frames occur faster than update frames, and this really doesn't need to run more than once a second, so no sense slowing the player down when it's already choking.

**Comment by jwvanderbeck** [comment]
Yeah basically, for performance reasons Update is better unless you absolutely need the fixed timestep.  Also IIRC this worked more reliably with timewarp.

**Comment by anxcon** [comment]
cool :)
