### ISSUE TITLE
1.5.0 Release

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#112]
stuff ready for 1.5.0

NEW mechanic (available to cfg modders) to use part data as science discounts in tech tree nodes the part is present in.

feature 96 PR
NEW failures for RemoteTech and parts using ModuleScienceExperiment

**Comment by jwvanderbeck** [comment]
In the future please use the Release Checklist: https://github.com/KSP-RO/TestFlight/blob/master/release_checklist.md

**Comment by anxcon** [comment]
ahhhh okie :P
