### ISSUE TITLE
Prepare 1.5.1 Release

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#115]
TestFlight Release 1.5.1.0
==========================

- [x] Determine proper version number
- [x] Verify good Travis build
- [x] Change log in Markdown
- [x] Github Release Tag
- [ ] Forum OP Change Log updated
- [ ] Forum OP Title updated
- [x] New reply in Forum thread with Change Log and any important notes

**Comment by jwvanderbeck** [comment]
1.5.1.0
----------
* **FIX**: Correct LR91 burn time cycles.
* **NEW**: Add LR91-AJ-3; fix LR87/91 config names for next RO
* **FIX**:  Fix ignition pressure curves, remove Agena and LR89/105 configs.
* **NEW**: Add AJ10 comments
* **CHANGE**: Update AJ10-early configs
* **CHANGE**: Update Examples.txt

**Comment by NathanKell** [comment]
@anxcon please fill out what you changed in Examples.txt (and anything else you've changed not in the above log)

**Comment by anxcon** [comment]
dunno how to do the nice old but 

Examples: Added example config for failures to FARControllableSurface module

**Comment by jwvanderbeck** [comment]
The forum thread got mangled really, **really** badly in the forum changeovers so might be worth making a new one.
