### ISSUE TITLE
Rework EngineModuleWrapper

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/TestFlight#117]
Now that everything derives from ModuleEngines, and EngineModuleWrapper has some Unity issues, this whole thing should be refactored.

**Comment by jwvanderbeck** [comment]
Needs KSP 1.1

**Comment by jwvanderbeck** [comment]
@NathanKell What was the 1.1 feature this was waiting on?

**Comment by NathanKell** [comment]
flow and isp multipliers in the engine module. No more changing g0.

**Comment by jwvanderbeck** [comment]
Implemented 5 years later
