### ISSUE TITLE
RP-0 and early solids

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/TestFlight#118]
As brought up in IRC, solids seem to have the same failure modes as liquid fueled engines.

Also, the reliability (at least of the Sepratrons and Baby Sergeants) is too damn low: Aiming for the Moon with a bundle of 12-4-1 baby sergeants has been most infuriating. Side note: how's the reliabilty of the FASA 11x Sergeant compared to 11 individual boosters?

Sepratron failures can be nasty when one tries to use them as ullage motor. In that role they tend to be throttled down, increasing their burn time long past the rated limit and making failure all but inevitable. No problem if the next engine can gimbal, but WAC upper stages are out.

I find that I actually like it if they shut down just a little too early, leaving a tiny remnant of solid fuel. That introduces just the right kind of error. Would it be possible to link their failure rate not to burn time, but to how little fuel is left?

**Comment by jwvanderbeck** [comment]
In general I think solids should be pretty darned reliable, but even one failure in a cluster can spell disaster.

Need to get some information on realistic failures on solids and how likely they are.

> Side note: how's the reliabilty of the FASA 11x Sergeant compared to 11 individual boosters?

That is config dependant, so it depends on how RO configured it.  I think @NathanKell did those configs.

Making them fail based on prop left is easy enough but i'm not sure it is very real.  As for engines that have been throttled down so they last longer, I am afraid I have no good answer on that one for the moment.  It is not easily handled by the system.

**Comment by anxcon** [comment]
engine reliability base on throttle would be fairly simple, just another reliability module, putting throttle to a floatcurve and adding result to reliability checks, as i did for maxQ effecting reliability - this brings into question realistic side of it, but since the effect would be up to a config that shouldnt matter

and throttle too high could hurt engines for sure,sadly throttle only goes to 100%

**Comment by jwvanderbeck** [comment]
You are talking about something completely different.

What is being discussed here is the reliability curve that intentionally curves up into insane momentary failure rates when an engine has exceed its rated burn time.  Lowering the throttle on an engine can push its actual burn time above its rated time and thus failure.

**Comment by NathanKell** [comment]
I managed to figure out a way to make MM disable the reduced thrust and shutdown failure modes on solids. I will likely be boosting the reliability a bit on those so configured, but @Schnobs do you have max data on them or are they at starting data levels? (Note that Baby Sergeant had a rather high failure rate if you look through the Juno I and II launches.)

**Comment by Schnobs** [comment]
I had quite some data, 307du -- after firing these 17, it was 326.

**Comment by NathanKell** [comment]
10,000 is max data. 326 is...almost none. Use the "parts have max data" cheat for now. :)

**Comment by Schnobs** [comment]
I guess a much higher multiplier might be in order.
I gained 19du from firing 17 of them (one failure); I guess that's (6 seconds * reliabilityDataRateMultiplier = 3) plus some rounding error? While firing, each individual engine went from 307 to 326. Except the failure of course. So I suspect that using several engines in one mission still only yields the single best result.

**Comment by jwvanderbeck** [comment]
There is a bug currently for multiple **parts** of the same engine.  Single parts that represent clusters are not affected but the config on them should have the appropriate data rate.

**Comment by jwvanderbeck** [comment]
> I managed to figure out a way to make MM disable the reduced thrust and shutdown failure modes on solids. 

Why do you need to disable it rather than just not adding it in the first place?

**Comment by NathanKell** [comment]
Because I don't want two sets of config generators. Easier to have one, and then delete the not-relevant-to-solids bit.
You can't do NODE:NEEDS[arbitrary value to be true], NEEDS is for checking mods installed. You can do:
NODE { moduleName = ShutdownEngine }
@NODE:HAS[solid] { @moduleName = disabled }
MODULE { name = ../NODE/moduleName }

**Comment by jwvanderbeck** [comment]
So confusing.  This is why I wrote the YAML preprocessor lol.  But hey if it works for you all good :)

**Comment by NathanKell** [comment]
Tuned reliability and data rates. Also support cluster multipliers now (higher failure chance but higher data rate).
