### ISSUE TITLE
Allow one minor and one major failure to occur on a given part

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#120]
when stuff fails, currently 2 things happen, either use oneShot flag and its a quick failure with nothing to fix (engine ignition failure) or something that breaks and requires fixing, shutting down the part in the process

should have a middleground, such as - if a blade breaks off of a prop, the engine gets unbalanced, should log the failure, but technically it still runs, and lets another failure happen

**Comment by jwvanderbeck** [comment]
TestFlight was **intentionally** designed to only allow a part to have one failure at a time for several reasons.

**Comment by anxcon** [comment]
things such as #128 leads to this abusing the minimal failures to gain longer/infinite life

while it could use the oneShot=true flag and not count as -the- thing to bring down the engine (or other part), that removes ability to repair it as it isnt logged. that leads to the argument whether or not such things should even be repairable, which is basicly game vs realism argument and why configs exist, so i'd skip that road. 

engines for example are also 2 /almost/ separate things, the engine and the gimbal, but nobody in their right mind will make that 2 parts in ksp, but dont really conflict so both can logically fail

welcome to add reasons why should remain 1 failure = dead

**Comment by anxcon** [comment]
could add a field to core, maxFailures, would allow stock configs or such to set to 1, while crazy people in RO can set to all

**Comment by jwvanderbeck** [comment]
Ok middle ground I think will work  Use the failure severity to allow one minor and one major failure to occur on a part.  

# Allow one Minor and one Major failure to occur on a given part

**Comment by anxcon** [comment]
what was wrong with config option to pick max failures per part? that lets it go every way, and a more flexible result

**Comment by jwvanderbeck** [comment]
v1.5.5.0 allows for multiple failures
