### ISSUE TITLE
core > disable failure > multiple of the failure module

### ISSUE THREAD

**Issue by anxcon** [KSP-RO/TestFlight#122]
it disables a failure by failure name, this instead should be some ID for the module, to not disable other potential failures of the same name on the part

**Comment by anxcon** [comment]
perhaps moving the disabled flag to the failure module itself?
when core fetches the failure modules, filter out the disabled

**Comment by jwvanderbeck** [comment]
What would be the point of having multiple of the same failure?

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by anxcon** [comment]
some parts have multiple ModuleGimbal for example for engines with multiple bells, in such cases you would only want to break 1 gimbal not all, so multiple modules 1 per gimbal transform

or as IRC had earlier, a part with 4x ModuleScienceExperiment - so 4 failures, each only enabled when its MSE module is operating

the main use to this, is to prevent an issue with an idea i had, during failure module load, if the required modules arent around etc, disable failure, so core doesnt try to trigger it

**Comment by jwvanderbeck** [comment]
But **one** failure should be handling the logic of all the respective pieces.  I don't see why you would define the same failure multiple times?  Just like the engine failures there is one failure and it has logic to handle the different engines.
