### ISSUE TITLE
Migrate TestFlight RO configs to RO project

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#124]
RO now has the ability to supply their own configs for TF, so having some configs in one place and some in the other is stupid.

Migrate all the configs from the TF project over to the RO project and remove them from TF.  Also need to update CKAN to remove the RO Configs from TF.

Will add a checklist here in a bit.

- [x] WAC Corporal
- [x] X-405
- [x] AJ10 Early
- [x] XLR11
- [x] XLR99
- [x] NAA-75-110-A
- [x] LR87
- [x] LR91
- [x] LR91-3
- [x] RL10
- [x] RL10x2
- [x] Update CKAN

**Comment by NathanKell** [comment]
Here is the example of how to use the generic configger.
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Engine_Configs/LMDE_Config.cfg#L174-L207
