### ISSUE TITLE
Alternate display of rated engine times

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/TestFlight#127]
The ideal location would be in the (RealFuels?) interface where you select between the engine variants, or in the hover text in that interface.

Currently, it is displayed only when you right click the part and scroll to the absolute bottom of the tooltip.

*Suggested Improvement*

**Comment by jwvanderbeck** [comment]
As a player using my mod I absolutely hate how it works in the editor.  I have plans to overhaul most if not all of the mod's UI come KSP 1.1 and this is definitely an area I will be looking at.

**Comment by jwvanderbeck** [comment]
This will happen sooner than 1.6.  The next version will include a new part info window that makes this information (and other TF data) more easily accessible.

I am still looking into how to integrate it with RF, though the `ratedBurnTime` is available as a KSPField so RF can grab it and use if desired.

**Comment by jwvanderbeck** [comment]
v1.5.4.0 adds a new info overlay window making this information more easily accessible.

**Comment by jwvanderbeck** [comment]
v1.5.5.0 adds RF integration
