### ISSUE TITLE
Loss of thrust is a very minor problem

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/TestFlight#128]
Naturally, failures tend to happen late in the burn. At that time, loss of thrust is often bearable / easy to compensate / possibly even beneficial.

NathanKell on IRC:  TF is presumably modeling a few things there. For pressure fed engines: loss of pressurization in the tank (slow leak, say). That would lead to slightly lower Isp, and lower flow.
Or, nozzle damage: lower Isp (so lower thrust but the same flow) or, turbopump failure leading to lower pump rate.

My personal favorite would be if the engine started using propellant unevenly, leading to less mass flow (loss of thrust) and some propellant left in the tank (less dV). Credible variations in fuel consumption will presumably have only a small effect on thrust, but the loss in dV will be serious.

**Comment by jwvanderbeck** [comment]
Yeah loss of thrust isn't modeled very well right now and does need to be reworked.

**Comment by jwvanderbeck** [comment]
@NathanKell you added a SetFuelIspMult to the engine wrapper.  Which way does that work?  increased multiplier is decreased Isp?  (That is what i'm guessing because increasing G would reduce Isp right?)

**Comment by jwvanderbeck** [comment]
1.5.3 will introduce a new failure mode that specifically reduces Isp performance

**Comment by jwvanderbeck** [comment]
Released in 1.5.3
