### ISSUE TITLE
Data still being gathered while rocket is connected to launch clamps

### ISSUE THREAD

**Issue by carbotaniuman** [KSP-RO/TestFlight#133]
This feels a little cheaty as I can just let the part I want to test run while connected to the clamps and get "free" data.

**Comment by jwvanderbeck** [comment]
This is/was intentional.  It is called static testing and is used in real life, so TestFlight simulated it.

That said with the upcoming R&D update, static testing will be removed.

**Comment by jwvanderbeck** [comment]
v1.5.4.0 has the new R&D system, and data can no longer be gained through static testing.
