### ISSUE TITLE
save settings in a safe place

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/TestFlight#137]
ModuleManager will rebuild it's ConfigCache whenever something changes in the Gamedata directory. It ignores folders named "PluginData" and everything inside, but any other changed file will trigger a cache rebuild.

Would be nice if settings.cfg (and other variable files that are of no concern to MM) could be moved to a PluginData folder.

**Comment by jwvanderbeck** [comment]
Fixed in: https://github.com/KSP-RO/TestFlight/commit/90c0055365ea673a4067d625da04668713c19834
