### ISSUE TITLE
Engine not getting proper time modifier

### ISSUE THREAD

**Issue by waerloga** [KSP-RO/TestFlight#140]
few seconds of debugging logs:

4 RD-107s: https://gist.github.com/waerloga/85e3245cfce8b3af1a56f35bc13c394c

2 RD-108s: https://gist.github.com/waerloga/a7d567b425d0d5975c3a617b3b504834

Synopsis: in 4 RD-107 had 1 failure (engine shutdown) after approximatly 2 minutes, after 5 minutes had loss of thrust. Ran engines for over 20 minutes, no further failures. 2 RD-108s ran fro 22 minutes, no failures, only gained 500 data units. from 7500.

Am running Test Flight 1.5.4.0

**Comment by jwvanderbeck** [comment]
Fixed in 1.5.4.2
