### ISSUE TITLE
Enable Flight HUD not persistant between launches

### ISSUE THREAD

**Issue by waerloga** [KSP-RO/TestFlight#141]
As title says, "Enable Flight HUD" setting on test flight is not kept between launches, instead resets to not enabled.

**Comment by jwvanderbeck** [comment]
Can you go to:
GameData/TestFlight/Plugins/PluginData

Verify that settings.cfg is present.  If it is, open it up and verify that the setting for "enableHUD" is present, and what is its values?

**Comment by jwvanderbeck** [comment]
Is this from a fresh install?

**Comment by jwvanderbeck** [comment]
Should be fixed with 1.5.4.4.  Isue was due to settings not being properly saved.
