### ISSUE TITLE
Flight Data always at 0 in VAB

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/TestFlight#142]
When I look at my parts on the launchpad or in flight/orbit, I can see the amount of Flight Data they have, however when middle clicking on a part, it just shows 0.00/10000.00 all the time.

**Comment by jwvanderbeck** [comment]
Looks like the partName being used to query the current data level is incorrect.  It is using the actual part name when it should be using the TF config name.

**Comment by rsparkyc** [comment]
I created a PR for this: https://github.com/KSP-RO/TestFlight/pull/143

**Comment by rsparkyc** [comment]
Looking at the work that's been done in dev, it looks like this PR is no longer needed, so i'll close it.

**Comment by jwvanderbeck** [comment]
Yep.  Thanks @rsparkyc appreciate it, but I tracked it down pretty quickly and it should be fixed in the next release.  Though right ow things are a bit wonky because i've been making some major changes.

**Comment by rsparkyc** [comment]
No problem, in the meantime i'm running a local copy with my one-line fix.

**Comment by jwvanderbeck** [comment]
Should be fixed in 1.5.5.  Please confirm with Beta 1 in the release section.
