### ISSUE TITLE
v1.8.0 doesn't load in KSP 1.1.3

### ISSUE THREAD

**Issue by chippydip** [KSP-RO/TestFlight#157]
This may be intentionally not supported since the update was specifically to support 1.2.2, but CKAN thinks it's supposed to work: 
![image](https://cloud.githubusercontent.com/assets/552649/24583178/aa8a28f2-16f6-11e7-8bdf-f4417f5a1458.png)

(There are type load exception in the log)

**Comment by jwvanderbeck** [comment]
TestFlight v1.8.0 is specifically compiled for KSP 1.2.2 so is most likely not compatible with KSP 1.1.3.  TestFlight 1.7.x should be.

This is probably an issue with the metadata for CKAN.
