### ISSUE TITLE
Engine Shutdown Easily "Fixed"

### ISSUE THREAD

**Issue by Starstrider42** [KSP-RO/TestFlight#160]
I've discovered that an "engine shutdown" failure can be fixed despite TestFlight no longer supporting repair functionality... sort of.

The bug can be reproduced in KSP 1.2.2, with ModuleManager 2.7.5, TestFlight 1.8.0.1, and [this config file](https://gist.github.com/Starstrider42/749685b1c0038d5d65916b286dafb7d1) instead of the default stock ones. I started a sandbox game, cheated the Orbiter 1A into orbit, and applied thrust until an engine failed. Right-clicking on the affected engine shows the normal "Activate Engine" button:
![screenshot4](https://cloud.githubusercontent.com/assets/6760782/25769129/e826a68c-31c6-11e7-9e4d-01aae0820cae.png)
Clicking it restores functionality to the engine, although the engine is still marked in red in the staging list and is still marked as failed in the TF window. However, it works just fine, and is immune to further failures:
![screenshot9](https://cloud.githubusercontent.com/assets/6760782/25769130/ebf08b3e-31c6-11e7-99c7-bb4d949424b8.png)

I suspect a similar bug applies to ignition failures, but I haven't been able to trigger one yet.

**Comment by jwvanderbeck** [comment]
Possibly something changed in 1.2 in regards to how you disable the engine.

**Comment by Starstrider42** [comment]
Update: I suspected at first that the code was merely missing the usual `Event.active = false` commands (which it was). However, adding

    engine.engine.Events["Activate"].active = false;
    engine.engine.Events["Shutdown"].active = false;
doesn't fix this bug. Debugging statements (using an independent way of accessing the PartModule) confirm that the events do get disabled; it's almost as if something else came along and re-enabled them afterward. This behavior seems to be unique to engines; e.g., the `Event.active = false` commands in `TestFlightFailure_LightBroken` do work.

That's about as far as I've gotten. I'm kind of stumped at the moment. 😞
