### ISSUE TITLE
Order matters for TF PartModules

### ISSUE THREAD

**Issue by Starstrider42** [KSP-RO/TestFlight#162]
The functionality of R&D depends on the order in which PartModules are defined for a part.

The bug can be reproduced in KSP 1.2.2 Windows 64-bit, with ModuleManager 2.7.6, TestFlight 1.8.0.1, and the following config file:

    @PART[liquidEngine3]
    {
        MODULE
        {
            maxData = 10000
            name = TestFlightCore
        }
        MODULE
        {
            name = TestFlightInterop
        }
    }

Starting a new sandbox game, going to the VAB, placing an LV-909 engine, and right-clicking on it shows the R&D button, as expected. However, editing the config to make `TestFlightInterop` appear before `TestFlightCore` and repeating the above procedure gives no R&D button.

KSP 1.2 changed how modules are started up; this bug may be related to that change in some way.

**Comment by jwvanderbeck** [comment]
Closing this not because it isn't valid, it might be, but because the R&D system has been removed and will be replaced with something different.
