### ISSUE TITLE
v.1.7.0.0 doesn't load in KSP 1.1.3

### ISSUE THREAD

**Issue by Elvaider** [KSP-RO/TestFlight#167]
Hello 

TestFlight refuses to load in KSP 1.1.3. I tried the CKAN installation as well as the those two downloads https://github.com/KSP-RO/TestFlight/releases/tag/1.7.0.0. According to CKAN the Module Mangaer 2.6.25 is installed. Funny thing is TestFlight shows up in the KSP-AVC. In the attachtments you can see a list with all of my curent mods.

Best Wishes

Elvaider
[mods.txt](https://github.com/KSP-RO/TestFlight/files/1013967/mods.txt)

**Comment by jwvanderbeck** [comment]
Log?

**Comment by Elvaider** [comment]
[KSP.txt](https://github.com/KSP-RO/TestFlight/files/1015972/KSP.txt)

**Comment by PhineasFreak** [comment]
From the log:

```
[EXC 10:34:22.439] FileNotFoundException: Could not load file or assembly 'RealFuels, Version=0.11.3.41637, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
	TestFlightRF.TestFlightRealFuels+<Setup>c__Iterator0.MoveNext ()
	UnityEngine.MonoBehaviour:StartCoroutine(String)
	TestFlightRF.TestFlightRealFuels:Start()
```

But RF is the correct one for KSP 1.1.3:

```
v0.11.3.1
```

And it is loaded correctly:

```
[LOG 10:27:09.302] RealFuels 0.11.3.1
.
.
.
RealFuels v0.11.3.1929 / v0.11.3.1               SHA256 41de9d416399b51680a59c45970951550362b896115acc709f9b8f5ee0f02274
```

Along with it's TF interop:

```
[LOG 10:34:20.113] AddonLoader: Instantiating addon 'TestFlightRealFuels' from assembly 'TestFlightRF'
```

**Comment by Elvaider** [comment]
so what shall I make out of this? Any sugestions?

**Comment by jwvanderbeck** [comment]
Can you try this version in stead please? https://github.com/KSP-RO/TestFlight/releases/tag/1.7.1.0.beta-1

**Comment by jwvanderbeck** [comment]
When you say it refuses to load, what specifically do you mean by that? What symptom are you using to say it isn't loading? No TestFlight button in SpaceCenter scene? Flight Scene? No engine support?

**Comment by Elvaider** [comment]
exactly I don't get any buttons at all. I even clicked once my aerobee engine to do some R&D but this button was gone as well
