### ISSUE TITLE
Not all TestFlight modules load for in-flight vessels

### ISSUE THREAD

**Issue by Starstrider42** [KSP-RO/TestFlight#169]
The bug can be reproduced in KSP 1.2.2, with ModuleManager 2.7.6, TestFlight 1.8.0.1, and [this config file](https://gist.github.com/Starstrider42/07d6784ee364ba66c10018bfb3fd4ec6). The fastest way to reproduce this bug is to create a new sandbox game, put the Kerbal 1 on the launchpad, exit to KSC, then resume the flight. Immediately after starting the flight, TestFlight will track both the command module and the second stage engine; after resuming from KSC, it will only notice the engine. There are no errors/warnings in the log, even with debug output enabled.

This bug is not associated with prelaunch status, and applies also to orbiting spacecraft. For example, if I launch the Kerbal 1 into orbit, the eventual TestFlight screen looks like this:
![screenshot3](https://cloud.githubusercontent.com/assets/6760782/26763956/65266b4c-4912-11e7-9e5a-e8d960ef87e2.png)
If I go to KSC and reload the flight through the tracking station, I get this:
![screenshot4](https://cloud.githubusercontent.com/assets/6760782/26763961/77ec0494-4912-11e7-9056-fb51329eb435.png)

This bug also applies if you quit KSP and later reload the save game.

I have not yet had a chance to try to isolate which TF modules are causing the problem; I'll post an update if I learn more.

**Comment by jwvanderbeck** [comment]
To be honest, TestFlight has never been good with switching vessels or scenes during flight.

**Comment by jwvanderbeck** [comment]
Closing in favor of https://github.com/KSP-RO/TestFlight/issues/225
