### ISSUE TITLE
Engine failures not restored on game load

### ISSUE THREAD

**Issue by Starstrider42** [KSP-RO/TestFlight#171]
Engine failure information does not appear to be persisted correctly across scene changes or game loads.

The bug can be reproduced in KSP 1.2.2, with ModuleManager 2.7.6, and TestFlight 1.8.0.1. Follow the procedure to reproduce #160, then either exit to the KSC and resume the flight from the tracking station, or quit KSP and reload the game. Although the engine is marked as failed in the [save file](https://gist.github.com/Starstrider42/34c173a79ae72bfc15630de100e203e8), the engine is marked as OK in the TestFlight window after loading the vessel. Though it is still shut down, if re-enabled it will never fail.
![screenshot1](https://cloud.githubusercontent.com/assets/6760782/26766018/846b105e-493d-11e7-9ce4-633fe3b9058b.png)

To ensure that none of the observed behavior is related to #160, I also replaced the shutdown failure in the config with `TestFlightFailure_EnginePerformanceLoss`. After repeating the procedure, letting an engine fail, going to the tracking station, and switching back to the ship, the failed engine had its full performance again (as shown by the lack of a net torque while under thrust).

**Comment by jwvanderbeck** [comment]
Closing in favor of https://github.com/KSP-RO/TestFlight/issues/225
