### ISSUE TITLE
Redesign Suggestion

### ISSUE THREAD

**Issue by hypermonkey** [KSP-RO/TestFlight#175]
I really wanted to like this mod, but after a couple of hours I uninstalled it. I just couldn't get a satellite into a high orbit (14,000 km) without it exploding. So I got to thinking how the mod could be reworked to make it possible to play with.

Normally part failures follow a [bathtub curve](https://en.wikipedia.org/wiki/Bathtub_curve) and this mod seems to model the constant failure rate within that (the bottom of the tub). I think that the mod should guarantee a part will work for that period. The failures can start to occur once the part reaches the end of its rated lifespan, with the chance of failure increasing at a constant rate. In this design the research/flight data should be used to increase the time the part is guaranteed to work for.

That would provide players with a guaranteed amount of time a part will work for and the ability to use a part beyond it's rated lifespan at increased risk. This would allow players to control their risk appetite for any given mission.

**Comment by jwvanderbeck** [comment]
This mod does use proper bathtub curve modeling but does not and will not ever guaruntee a part will work in the "bottom" part. Not even everyday items are 100% reliable, let alone rocket parts under high stresses.  There is always a chance, even if it is small, that it will fail.  It also would completely defeat the core point of this mod which is "fly test flights to improve reliability"

If you couldn't get a satellite into high orbit after hours of trying then either you were running engines far past their rated time (the upside on the end of the bathtub curve) or were using bad engines, or not flying test flights to improve them.
