### ISSUE TITLE
Lag spikes in VAB in version 1.9.0.0

### ISSUE THREAD

**Issue by laukejas** [KSP-RO/TestFlight#189]
With KSP 1.3.1, Realism Overhaul and related mods, as well as TestFlight 1.9.0.0, I am getting lag spikes in VAB/SPH, and the debug log filled with messages like:

[LOG 00:17:51.329] 2/25/2019 12:17:51 AM,TestFlightCore,DEBUG: PMExtended OnSave

Steps to reproduce:

1. Open VAB/SPH, create a new craft, add some parts;
2. Open the log window (alt+F12)
3. Add, remove, move or otherwise interact with any part, and the log gets flooded with PMExtended OnSave messages, causing lag spikes.

Full mod list (on PasteBin): https://pastebin.com/Q1dXqa5k

Is there any way to fix this?

**Comment by jwvanderbeck** [comment]
Sounds like you are using debug compiled versions of the plugin

**Comment by laukejas** [comment]
I was using the TestFlight from the link in the Releases section: https://github.com/KSP-RO/TestFlight/releases/download/1.9.0.0/TestFlightCore-1.9.0.0.zip

Is this a debug build? If so, where can I find the non-debug one?

**Comment by jwvanderbeck** [comment]
@pap1723 Can you look at this please? Looks like the release was done by you. Did you compile the DLLs or did someone else?

**Comment by pap1723** [comment]
Yep, looks like there might have been a mistake for sure. We will be releasing a new version very soon!

**Comment by laukejas** [comment]
@pap1723 thanks a lot! Really looking forward to it.

**Comment by siimav** [comment]
Looks like Pap never got around to making a new release. Anyway, an update is now up and was compiled in the *Release* mode.
