### ISSUE TITLE
TestFlight refused to install

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-RO/TestFlight#191]
Problem:

TestFlight installation REQUIRES either RO/Config Stock.  However, when installing with Config Stock, CKAN will abort the install because TF installs first and includes: 

~/TestFlight/Config/ignore.txt

Solution:

Remove 'ignore.txt' from either TestFlight core. Since it is ostensibly a configuration file, it would (and should) be provided by any future config packs.

**Comment by jwvanderbeck** [comment]
To be honest, RO stopped officially supporting Stock configs a very long time ago as no one wanted to contribute to them.

**Comment by 7ranceaddic7** [comment]
Irrelevant, this is not an issue of properly supported/non-supported configs.  It is an ill-place file that prevents proper installation.

**Comment by jwvanderbeck** [comment]
The stock configs are too far out of date.  They don't even work properly anymore.  If they were allowed to be installed then people would then just complain that they don't work.

Unless someone updated them to be working again?

**Comment by 7ranceaddic7** [comment]
Respectfully, the problem has NOTHING to do with the config files themselves.

**Comment by HebaruSan** [comment]
A zero byte "ignore.txt" file doesn't belong in any mod archive. I'd recommend removing it from both.

**Comment by jwvanderbeck** [comment]
I wouldn't just randomly create an ignore.txt file.  There has to be a reason I did it, even if I can't recall what it was all these years later.  My guess is it was there to prevent an empty directory.

But my understanding is it the file isn't the problem but the fact that the directory exists at all?  Why does CKAN not have a "Force" or some such option to install even if the directory exists?

As I don't actively maintain this anymore, I'm not currently set up to build this project so best I can do is remove the folder and **hope** it doesn't cause any problems whenever the next release is made.

**Comment by HebaruSan** [comment]
> There has to be a reason I did it

It looks like an artifact of trying to commit an empty folder in git, which isn't needed for a mod release ZIP.

**Comment by jwvanderbeck** [comment]
> > There has to be a reason I did it
> 
> It looks like an artifact of trying to commit an empty folder in git, which isn't needed for a mod release ZIP.

Yeah so the reason the file is there is so that the folder doesn't get deleted.  This is because it is necessary for the CI scripts.  Removing that file, makes the folder go away which breaks CI. 

This is because the stock configs are created dynamically by a python chaser.

So to fix this I have to rewrite how the whole process works.

**Comment by jwvanderbeck** [comment]
Fixed with #197
