### ISSUE TITLE
Integration with RP-1 Spyware

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#229]
Talk to @siimav for details

**Comment by jwvanderbeck** [comment]
https://github.com/KSP-RO/RP-0/commit/c3a5d8ec1c85c0cd5d4a23b74ee29b85ee44961c

**Comment by siimav** [comment]
Now available as PR: https://github.com/KSP-RO/RP-0/pull/1542

**Comment by siimav** [comment]
Implemented in #248
