### ISSUE TITLE
Add current rated burn time to PAW for engines

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/TestFlight#234]
TL has the burn time in its PAW UI in VAB, which is a nice quality as it saves me jumping into the engine selection UI to hover over it and read.  /featurerequest  /wishlist

**Comment by jwvanderbeck** [comment]
Are you another 2 button mouse person?

**Comment by Bornholio** [comment]
nope just play often enough to forget that the feature exists, since its not obvious

**Comment by lpgagnon** [comment]
doesn't realfuels itself add the rated burn time to the PAW now?

**Comment by Bornholio** [comment]
RF, 13.0 doesn't seem to, https://i.imgur.com/bfivr7Z.png

**Comment by pap1723** [comment]
It worked for the version of TL I was using, but I just switched to TF today and no Burn time showing for me

**Comment by Bornholio** [comment]
Should I move this request to RF?

**Comment by NathanKell** [comment]
I'd tend to favor not doing so, only because it's irrelevant without TF or TL (and some engines don't have one), but if you think it makes more sense there I can be persuaded. :)

**Comment by al2me6** [comment]
Working on it. Also doing a bonus thing:

![image](https://user-images.githubusercontent.com/35266431/124539851-3bc94a80-ddec-11eb-9207-ef9a42bfc326.png)

**Comment by Capkirk123** [comment]
Seeing as RF now displays rated burn time in it's own UI, is this good to be closed? Or does @al2me6 want to keep it open for the burn time planner?
