### ISSUE TITLE
AddOn proposal

### ISSUE THREAD

**Issue by pack7df** [KSP-RO/TestFlight#255]
I have an idea for TestFlight creating an AddOn, i think i have a better idea of how to do it and how much it would cost, the problem is i have no experience creating mods in KSP.

Can i send a document with my idea and you can give me hints about how to do it with this mod?

**Comment by Capkirk123** [comment]
Would you care to elaborate further on what you mean by "AddOn"

**Comment by pack7df** [comment]
I think i read this in your own documentation, it's to create a mod using your own API, it would be an extension of your mod.

**Comment by Capkirk123** [comment]
Of course. Documentation for TestFlight can be found in [the wiki](https://github.com/KSP-RO/TestFlight/wiki), and also in the source code itself. You're welcome to develop an addon which interacts with TestFlight using the TestFlight API.

**Comment by pack7df** [comment]
But can i send you a document with the idea and formula? I have never develop a mod for KSP and i would like you give me some minor guidance, not a guide, just advices, and where to look at in the api.

**Comment by NovemberOrWhatever** [comment]
We aren't going to walk you through the entire process of making a mod, and tracking down or creating a formula is not exactly a significant portion of the development process. If you are interested in modding KSP, find something easy that you can start with. I'm sure there's something simple you can try out on your own. Having ideas is a lot easier than implementing them.

**Comment by pack7df** [comment]
Thats exactly why ask for a little advice, not the entire process, but it's ok, i will try by my self.
