### ISSUE TITLE
thrustModifier uses wrong Isp curve for throttle calculation

### ISSUE THREAD

**Issue by ec429** [KSP-RO/TestFlight#258]
I think I found out why `thrustModifier` isn't working in TF: it's using `atmCurveIsp.Evaluate(0f)` as part of its "throttle ratio" calculation (`EngineModuleWrapper.commandedThrust`), but that always returns 0.  In TL I'm now using `atmosphereCurve` instead and it seems to work.

(Related: on https://github.com/KSP-RO/TestFlight/wiki/Module-Reference:-TestFlightReliability it claims that the keys to the curve are "thrust in kN"; AIUI that's incorrect.)

**Comment by Capkirk123** [comment]
Resolved with #252
