### ISSUE TITLE
2 stages with same engine loses DU

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/TestFlight#259]
Haven't been able to pinpoint steps; couldn't deliberately reproduce. But I've seen it happen twice now:

Given a 2-stage LV with a TLI stage on top; 2nd stage and TLI stage use same engine, with different burn times. Concrete example: rd0105, 400s and 50s

In flight, TF window shows each engine earning its expected amount of DU as each burn; +~500 vs +~60

Back at space center after mission, go to VAB, start a failures-enabled sim with a rd-0105 to check DU amounts (possibly can also just check DU in VAB middle-click window): instead of earning either the sum of both earned values or the higher of the two, I see the engine has only been credited the DU from the last, short-burning stage.

**Comment by siimav** [comment]
Hopefully fixed now. I added a check that would prevent DU getting set to a lower value than it used to be.
