### ISSUE TITLE
PAW Ignition Chance broken for solids

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/TestFlight#262]
2.3.0's new reliability-in-PAW feature is partially broken for SRMs: the "ignition chance" fields are always zero. Other fields look fine; Ignition Chance is fine for liquide-fueled engines

All SRMs seem affected; I checked RO's small sep motor and all Scout stages.
<img width="547" alt="Screenshot 2023-01-12 at 20 23 45" src="https://user-images.githubusercontent.com/5061230/212215849-36f8aeee-c9a4-4666-bb0f-619b6e4f301a.png">

Only happens in VAB; chance is non-zero in flight scene and appears correct.

**Comment by jwvanderbeck** [comment]
Do solids even have an ignition fail module?  I mean they can't fail to
ignite can they?

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by lpgagnon** [comment]
they do and they can. 

https://github.com/KSP-RO/RealismOverhaul/blob/8a2d84902e29d2a968dc1c03aeddbb996e35885c/GameData/RealismOverhaul/Engine_Configs/Castor_1_Config.cfg#L276-L283

<img width="198" alt="Screenshot 2023-01-12 at 21 21 11" src="https://user-images.githubusercontent.com/5061230/212222238-0d251c5a-d997-4ca0-838e-4a23ae34786c.png">

```
		MODULE
		{
			name = TestFlightFailure_IgnitionFail
			configVersion = 2
			CONFIG
			{
				configuration = Antares-I
				additionalFailureChance = 0.2
				restoreIgnitionCharge = False
				duFail = 1050
				oneShot = True
				failureType = mechanical
				failureTitle = Failed to ignite
				ignorePressureOnPad = True
				severity = major
				pressureCurve
				{
					key = 0 1 0 0
				}
				baseIgnitionChance
				{
					key = 0 0.91129
					key = 3000 0.964516 4.81568571428571E-06 4.81568571428571E-06
					key = 10000 0.982258 0 0
				}
				restartWindowPenalty
				{
					key = 0 1
					key = 1 1
				}
			}
		}
```

in flight scene:
<img width="256" alt="Screenshot 2023-01-12 at 21 24 30" src="https://user-images.githubusercontent.com/5061230/212222643-f67ce13f-5160-4352-b62f-0128849222db.png">

**Comment by Falki-git** [comment]
PR https://github.com/KSP-RO/TestFlight/pull/263 will fix the issue

**Comment by Falki-git** [comment]
Tested it a bit more in my gaming instance, works good now with https://github.com/KSP-RO/TestFlight/pull/263
