### ISSUE TITLE
TestFlight RD-100/101 Status & Cause paw messages do not refresh

### ISSUE THREAD

**Issue by bofhgr** [KSP-RO/TestFlight#275]
![screenshot0](https://github.com/KSP-RO/RP-1/assets/28956359/a592bc1d-d0ea-4b7a-b282-fbf1aadf19c0)

It might be the same with other engines, have only tested and confirmed this with the RD-100/101.

The Status and Cause messages on the paw for the engine show the correct status until you get a failure. Subsequent flights will always show the status: Failed and Cause: Engine Shutdown even if this is a new vehicle built after the failure. It seems like these status messages are not unique for the vehicle.

In the attached screenshot you can see the status messages when the rocket is actually flying fine.

Playing on hard with pre-flight failures enabled if that makes any difference

**Comment by siimav** [comment]
> new vehicle built after the failure

Could you please be more specific about that. Did you roll the vessel back and replace the engines? Did you save the craft file after rollback but before switching out the engines?
The thing to keep in mind is that failures will get stored in craft files and thus persist on future vessels if using said craft file.

**Comment by siimav** [comment]
I now fixed an issue where failures didn't actually apply after a scene change. Next time something like this pops up, we'll at least see if there's an actual underlying failure or if it's just that status text being wrong.
