### ISSUE TITLE
Make dynamic pressure failures enabled by default

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/TestFlight#276]
As titled, per discussion w/NK on stream.

**Comment by siimav** [comment]
Done in 27834ee8a1aa1ad297a68f5a0c35609d6ce5b600

**Comment by jwvanderbeck** [comment]
I can taste the tears already

**Comment by Test-Account-KSP** [comment]
The setting has no effect on gameplay unless one uses incorrect designs that need to ignite in the atmosphere.
The only reasonable craft that is affected are rocketplanes with non-rocketplane engines. These need to drop speed before ignition to avoid dynamic pressure failure risk.

**Comment by jwvanderbeck** [comment]
Yes I'm aware of how it works :)

- John Vanderbeck
- http://www.johnvanderbeck.com
