### ISSUE TITLE
Cycle failures from parts in PRELAUNCH shouldn't generate DU

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/TestFlight#278]
Just running engines properly doesn't generate du, but apparently cycle failures still do.
(Note: ignition failures do too, but that's proper.)

**Comment by arrowmaster** [comment]
It might be good to limit the ignition failures to only generating DU on single ignition engines or some other way to prevent spamming ignitions for the engines with a high ignition count.

**Comment by asdfugil** [comment]
for this purpose, ground support clamp engines has unlimited ignitions as long as they are clamped

**Comment by KEKKJ123** [comment]
I discussed my viewpoint in this issue. https://github.com/KSP-RO/RP-1/issues/2047
I think that launch pad testing should be reduced in revenue, but should not be prohibited.(or cheese)

**Comment by siimav** [comment]
Implemented in c4837fa13d12e40fb1cab994d65193fe776f0598
