### ISSUE TITLE
0Pa dynamic pressure caused a 100% reduction in normal ignition reliability

### ISSUE THREAD

**Issue by RubenOllesch** [KSP-RO/TestFlight#279]
Hi,

I am currently attempting a Ranger-style mission in RP-1 but am repeatedly running into "Ignition Failure: 0Pa dynamic pressure caused a 100% reduction in normal ignition reliability".

As far as I understand it, high dynamic pressure reduces the ignition chance so that lighting rocket engines deep inside the atmosphere is discouraged.

My craft however is currently in a 160km orbit without any atmosphere - thus 0Pa dynamic pressure -, so I don't quite understand the issue.

Is this a bug or am I missing something?

I have already tried quicksaving & reloading about 10 times, with one "normal" ignition failure but otherwise always a failure due to dynamic pressure.

## Version Info
KSP 1.12.3.3173 (LinuxPlayer) en-us
        1.12.1 Making History
        1.7.1 Breaking Ground
### RP-1 Mods
RP-1 Express Install v2.0
RP-1 v2.10.0.0
Test Flight v2.6.1.0
### Additional Mods
Trajectories v2.4.5.2
Docking Port Alignment Indicator 6.10.0.0

See full list:
[Installed Mods.txt](https://github.com/KSP-RO/TestFlight/files/12514337/Installed.Mods.txt)

## Screenshots
Before ignition attempt
![screenshot9](https://github.com/KSP-RO/TestFlight/assets/42176443/02d1a398-f7f0-4457-838f-07c5e17a6248)
After ignition attempt
![screenshot13](https://github.com/KSP-RO/TestFlight/assets/42176443/bd5dc94a-52eb-4a19-a2c5-29ac3ebd3a94)

**Comment by RubenOllesch** [comment]
In my save I worked around the issue by editing the save file and resetting the XLR81 back to 2 ignitions from 1 (the first was used for orbital insertion).
Weirdly enough, this prevented the failure from occuring.

**Comment by siimav** [comment]
Looks like the dynamic pressure message in flight log is just wrong and the real issue is here:
![image](https://github.com/KSP-RO/TestFlight/assets/1120038/96205fd8-03b5-43e3-a8a2-58b90595e260)

Some engines have penalties based on how much time has passed since last ignition. Agena is one of those where chance will drop after some time and then restore to full again after some hours have passed. I think middle clicking on the engine in Editor will reveal this information.

**Comment by RubenOllesch** [comment]
Oh ok, I get it - so it was just a case of a confusing message combined with me not knowing how my spacecraft is supposed to behave.
Thanks for quick reply!
