### ISSUE TITLE
KW Rocketry engines do not gather data.

### ISSUE THREAD

**Issue by icedown** [KSP-RO/TestFlight#85]
Already mentioned this in forum post. No engines in the KW rocketry pack gather data while operating.  This is true for both LFO, SRB, and HG.

**Comment by jwvanderbeck** [comment]
Hey @icedown can you share the configs you had when you encountered this bug please?

**Comment by OzoneGrif** [comment]
I had the same bug today. 
Not only they don't gather data, but they don't activate at all during staging.
The Maverick has this problem, for example.

I've also had a problem with the LV-909 not activating during staging. I had to right-click on the reactor to activate it manually.

Another bug (which is probably linked with all these troubles) is a strong lag during staging, sometimes causing the sound to loop for half a second.

**Comment by jwvanderbeck** [comment]
Possible due to the divergence of dev and master, where dev had more up to date engine configs.

DEV branch has been merged to master and those new configs will go live with the next release

**Comment by jwvanderbeck** [comment]
This is an old issue which should be fixed.  If anyone is still encountering this bug please open a **new** issue.
