### ISSUE TITLE
Does TestFlight dev need to be merged to master?

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#92]
@NathanKell 

There appear to be a lot of config changes in Dev that were never merged to master, including a lot of engine stuff.  Presumably that should be merged, but I can't recall that well and it seems off that things would be working correctly if all those changes were missing?

Can you shed any light?

https://github.com/KSP-RO/TestFlight/compare/cbb51e4b3b655008065d70ef87d23988005640cc...892d3664d69b018f4a61d175ffd6f037fe335b07

**Comment by NathanKell** [comment]
As it happens, things are _not_ working right with engine configs, though the plugin itself seems ok. So that would explain it, since I coulda sworn I _had_ updated those engine configs. :)

**Comment by jwvanderbeck** [comment]
Gotcha.  I've recompiled TestFlight for v1.0.5 and will merge dev into master

**Comment by NathanKell** [comment]
Great! :)

**Comment by NathanKell** [comment]
btw I _did_ add stock ModuleEngines flow and Isp mults for you. :)

**Comment by jwvanderbeck** [comment]
I'm sure it was for a good reason that I can't remember now :)

**Comment by jwvanderbeck** [comment]
Closing this since it is resolved
