### ISSUE TITLE
Prepare v1.4.0 Release

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#93]
TestFlight Release 1.4.0.0
==========================

- [x] Determine proper version number
- [x] Verify good Travis build
- [x] Change log in Markdown
- [x] Change log in BBCode
- [x] Github Release Tag
- [x] Uploaded to KerbalStuff
- [x] Forum OP Change Log updated
- [x] Forum OP Title updated
- [x] New reply in Forum thread with Change Log and any important notes

**Comment by jwvanderbeck** [comment]
Change log for 1.4.0

* **FIX**: Fixes Issue #82 LR-105 engine misconfigured in RO configs
* **NEW Configs**: Added LR-91 (-5, -7, -9, -11, -11A models) configs to the FASA Gemini LR-91 model.  **Thanks @stratochief66!**
* **API Changed**: `baseFailureRate` and `momentaryFailureRate`, as well as momentary failure rate modifiers are all treated internally as doubles now for extra precision with very small failure rates. All API calls utilizing any of these values now return and expect doubles.
* **NEW Configs**: Added new property to TestFlightCore,
`failureRateModifier` which defaults to 1.  This is a flat, fixed,
modifier applied to the calculated baseFailureRate which can be used to
force smaller values than is possible normally due to 32 bit
restrictions in KSP.
* **NEW**: In order to accommodate very small failure rates, the core
has been reworked to use 64 bit double precision floats internally.
This allows failure rates as low as .00000000000001.  However, KSP
itself will not persist doubles, only floats.  Further more, by their
very nature FloatCurves, which are used to define the failure rate
curves, have to be floats.  This means that while internally the
failure rate can be much lower than before, KSP will still only allow
you to specify failure rate values down to .0000001 (This is one
significant digit lower than previous).  In order to get even smaller
values than that, use the new property on TestFlightCore
`failureRateModifier` to force it even lower.  Setting both the
failureRate and the failureRateModifier to the smallest float value of
.0000001 will result in a calculated failureRate internally of the min
rate, .00000000000001
* **CHANGED Configs**: Update RO configs for RO 10.0
    * Aerobee configs were renamed
    * RL, AJ, and LR no longer have a dash (Only the last was relevant here)
* **NEW**: Recompiled for KSP v1.0.5

**Comment by jwvanderbeck** [comment]
@NathanKell Since it has been ages for both you and I, need to clarify this statement you made in PR https://github.com/KSP-RO/TestFlight/commit/34a3e31c40876f3a22d0c78c3cfb648d4253fee1

@jwvanderbeck : I did not go ahead and copy the LR89 configs to the
LR79/H-1/RS-27, but those new configs should be supported too and they
are broadly comparable to LR89 configs. Note that I did finally separate
LR79 and LR89

**Comment by jwvanderbeck** [comment]
BBCode Change Log
-----------------------------


[SIZE=4][B]Release 1.4 (v1.4.0.0)[/B][/SIZE]
[URL="https://github.com/KSP-RO/TestFlight/releases/tag/1.4.0.0"]GitHub[/URL], or [URL="https://kerbalstuff.com/mod/572/TestFlight"]KerbalStuff[/URL]

[SIZE=3][B]Highlights[/B][/SIZE]

[B]KSP v1.0.5 Compatible[/B]

[B]Project is now part of KSP-RO![/B]
First I want to apologize to everyone for, well, just vanishing, like I did.  I started a new job a while back and quickly just got completely busy and overwhelmed and just stopped doing anything KSP related, including working on my mods.  Things aren't as busy for me anymore, but frankly in all this time I have drifted far away from KSP and in fact am now working on my own game!

Now what does that mean for TestFlight?  While I am not actively working or support this mod anymore, I am still around.  TestFlight has been moved into the KSP-RO family where it can be more easily maintained by multiple people, and I will continue to provide support and pieces of development *when able*.  In short, you can still enjoy this wonderful (if I do say so myself) mod, but it will be in more of a maintenance mode rather than mad active development like it was in the past.

New configs will be coming down the pipe shortly to allow TF to be used in even more parts.

[B][SIZE=3]Change Log[/SIZE][/B]

•[B]FIX[/B]: Fixes Issue #82 LR-105 engine misconfigured in RO configs
•[B]CONFIGS - RO[/B]: Added LR-91 (-5, -7, -9, -11, -11A models) configs to the FASA Gemini LR-91 model. Thanks @stratochief66!
•[B]API[/B]: baseFailureRate and momentaryFailureRate, as well as momentary failure rate modifiers are all treated internally as doubles now for extra precision with very small failure rates. All API calls utilizing any of these values now return and expect doubles.
•[B]CONFIGS - ALL[/B]: Added new property to TestFlightCore, failureRateModifier which defaults to 1. This is a flat, fixed, modifier applied to the calculated baseFailureRate which can be used to force smaller values than is possible normally due to 32 bit restrictions in KSP.
•[B]NEW[/B]: In order to accommodate very small failure rates, the core has been reworked to use 64 bit double precision floats internally. This allows failure rates as low as .00000000000001. However, KSP itself will not persist doubles, only floats. Further more, by their very nature FloatCurves, which are used to define the failure rate curves, have to be floats. This means that while internally the failure rate can be much lower than before, KSP will still only allow you to specify failure rate values down to .0000001 (This is one significant digit lower than previous). In order to get even smaller values than that, use the new property on TestFlightCore failureRateModifier to force it even lower. Setting both the failureRate and the failureRateModifier to the smallest float value of .0000001 will result in a calculated failureRate internally of the min rate, .00000000000001
•[B]CONFIGS - RO[/B]: Update RO configs for RO 10.0
    [INDENT]
    •Aerobee configs were renamed
    •RL, AJ, and LR no longer have a dash (Only the last was relevant here)
    [/INDENT]
•[B]NEW[/B] Recompiled for KSP v1.0.5

**Comment by NathanKell** [comment]
I believe that, roughly, the LR89 configs should be copied over, since they make a decent base for LR79 configs. They need somewhat longer rated burn times however, IIRC.

**Comment by jwvanderbeck** [comment]
Merged in TestFlightExtended from @anxcon which adds tons of new failure modules.  

Before doing a release, I would really appreciate some testing of Master under KSP 1.0.5

**Comment by anxcon** [comment]
basic tests (though rushed) looks like everything works - failure modules added had no configs yet, but my test configs worked to break things as intended :) i too am bad at supplying the configs lol not worth holding up the release for though

guess il switch focus to makin configs for 1.5 release, instead of breaking things :)

**Comment by jwvanderbeck** [comment]
Going to shoot for getting this out this weekend.

**Comment by jwvanderbeck** [comment]
Having some issues compiling your additions @anxcon .  Looking into it a bit more now.

**Comment by jwvanderbeck** [comment]
Dur my fault.  Need to get a couple of things up to date I guess.

**Comment by jwvanderbeck** [comment]
Updating Release Notes with:

* **FIX**: Really updated to KSP 1.0.5 this time
* **CHANGED**: Updated ContractConfigurator to 1.8.1
* **NEW**: Added support for lots of different parts thanks to the awesome work of @anxcon.  New part support includes: Avionics, Docking Rings, FAR Control Surfaces, Gimbals, Reaction Wheels, Solar Panels, Heat Shields and more! **Major thanks to @anxcon**

**Comment by jwvanderbeck** [comment]
Looks like there are still some lingering issues with the auto build system after the repo move.  Going to need to find and fix them then do a new point release.

**Comment by jwvanderbeck** [comment]
Still trying to fix this.  Travis seems to insist on seeing the old repo no matter what I do :(

**Comment by jwvanderbeck** [comment]
Finally fixed it.  Stubborn little sucker.

**Comment by jwvanderbeck** [comment]
Done.  Release 1.4 is out!

**Comment by NathanKell** [comment]
Woot!

**Comment by stratochief66** [comment]
I concur! 

I will do some testing of this this week. I agree with NathanKell's idea that LR89 configs should be copied over. I would extend that idea to applying a similar generic template to basically every engine as a start, or perhaps having things setup so that it uses that by default if no other data is configured for an engine?

I know the reality is much more complicated than that, as for TestFlight to fly true it needs to know which engines inherit reliability from the testing of other engines, but it might be a good 0th step?

Like I said, I am going to be testing this this week and looking at creating/modifying templates so I have more than a remote idea for helping and making organizational suggestions.. I'm not afraid of YAML, I just currently suck at it. :P
