### ISSUE TITLE
Engine Templates

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/TestFlight#94]
As discussed here: https://github.com/KSP-RO/RP-0/issues/311 in order to make adding engine configs easier, it would be good to define some broad templates that could then be assigned to multiple engines.

So I see this as a two part process.  First we need to identify the various engine templates we want, and then secondly we need to write the configs for those templates.

So let's see some discussion on which templates to define. @NathanKell @stratochief66

**Comment by NathanKell** [comment]
I would think relevant bits would be type and era
So Booster-Early would set up an engine that ground lights (but doesn't air light), that has an expected burn time of 3 minutes, and that starts at moderate reliability and ends at good reliability. Upper-Pump-Early would have a burn time of 6 minutes, does not ground light or air light but does vacuum light, and has middling reliability. Upper-Pressure-Early has a burn time about that, maybe only 5 minutes, same on lighting environment, but has very good reliability.

The mid and late versions would start, and end, at higher reliability, and perhaps have longer rated burns.

I see no particular need to differentiate by propellant mixture, except perhaps to give hydrolox engines a lower starting reliability (but equivalent ending reliability).

**Comment by jwvanderbeck** [comment]
So something like this?

[ ] BoosterEarly
[ ] BoosterMid
[ ] BoosterLate
[ ] UpperPumpEarly
[ ] UpperPumpMid
[ ] UpperPumpLate
[ ] UpperPressureEarly
[ ] UpperPressureMid
[ ] UpperPressureLate

**Comment by jwvanderbeck** [comment]
> I see no particular need to differentiate by propellant mixture, except perhaps to give hydrolox engines a lower starting reliability (but equivalent ending reliability).

Sounds like a good reason to me no?

**Comment by NathanKell** [comment]
Yeah, I think that list makes sense, though I would double up on booster and upper/pump for the hydrolox versions.

What I meant is that there's no need for BoosterStorable vs BoosterKerolox vs BoosterHydrolox, and there's no need for pressure versions of hydrolox.

**Comment by stratochief66** [comment]
Sorry, away for a while.

I agree with all that has been said so far!

**Comment by jwvanderbeck** [comment]
Work should be done in this branch: https://github.com/KSP-RO/TestFlight/tree/Feature_94_EngineTemplates

**Comment by jwvanderbeck** [comment]
So turns out there may be a catch in doing this after all, due to the way the system works with RO configuration definitions.  I need to ponder.

**Comment by jwvanderbeck** [comment]
Ok so here is an example of **using** a predefined template to **make** a config for a **specific** engine.  How does this look?

    WAC-Test: &WAC-Test
        -   name: 'ConfigurationOverride'
            configuration: 'WAC-Corporal'
        -   name: 'TestFlightInterop'
        -   name: 'TestFlightCore'
            maxData: 10000
            configuration: 'engineConfig = WAC-Corporal:WAC-Corporal'
            title: 'WAC Corporal'
            startFlightData: 500
        -   *BoosterEarly-Reliability
        -   *BoosterEarly-EngineCycle
        -   *BoosterEarly-DataRecorderEngine
        -   *ShutdownEngine        
        -   *BoosterEarly-ShutdownEngine
        -   *IgnitionFail
        -   *BoosterEarly-IgnitionFail
        -   *ReducedMaxThrust
        -   *BoosterEarly-ReducedMaxThrust
        -   *Explode
        -   *BoosterEarly-Explode

**Comment by jwvanderbeck** [comment]
So the code to do this is in there now.  So what we need are people to work out the templates, or at the very least the desired numbers if everyone is too afraid of the YAML :)

**Comment by jwvanderbeck** [comment]
Here is an example template: https://github.com/KSP-RO/TestFlight/blob/Feature_94_EngineTemplates/configs/RealismOverhaul/RO_Engines.yaml#L2223-L2275

However the numbers are probably completely wrong

If anyone wants to start working on templates please do it in that "Feature_94_EngineTemplates" branch.

**Comment by stratochief66** [comment]
I will do some testing of this this week. I agree with NathanKell's idea that LR89 configs should be copied over. I would extend that idea to applying a similar generic template to basically every engine as a start, or perhaps having things setup so that it uses that by default if no other data is configured for an engine?

I know the reality is much more complicated than that, as for TestFlight to fly true it needs to know which engines inherit reliability from the testing of other engines, but it might be a good 0th step?

Like I said, I am going to be testing this this week and looking at creating/modifying templates so I have more than a remote idea for helping and making organizational suggestions.. I'm not afraid of YAML, I just currently suck at it. :P

**Comment by stratochief66** [comment]
@anxcon sent me this code @jwvanderbeck , could something like this be used to provide a super-generic catch-all for engines that haven't been customly configured or set to templates yet?

http://www.hastebin.com/ivaqodoriw.vbs

**Comment by stratochief66** [comment]
I am unsure why, but despite showing (FASA) LR-87 TestFlight data in the VAB for all of the configs, TestFlight never seemed to detect that it was a TF compatible engine.

**Comment by stratochief66** [comment]
@jwvanderbeck 

Alright, I think I have a decent idea of how the templates appear to work. I will set up my computer to be able to test YAML changes I make later this week so I can test creating and applying new templates.

So normal configs have techTransfer, where you explicitly state which other config names should be linked to this config. If two engines share a template, will that techTransfer automatically happen, or will that need to be defined either in the Template creation or Template usage?

**Comment by jwvanderbeck** [comment]
> @anxcon sent me this code @jwvanderbeck , could something like this be used to provide a super-generic catch-all for engines that haven't been customly configured or set to templates yet?

The problem with "catch all" configurations is the way TF ties into RO.  Parts like engines or procedural parts that can change at runtime get a little tricky.  That is why the modules have the `configuration` property, to help TF know how connect to changes at runtime.  I'm not sure of the complexity of making a catch all given this bit, but considering how easy it will be to knock out generic engines using the templates, I don't think it is worth the added complexity.

> So normal configs have techTransfer, where you explicitly state which other config names should be linked to this config. If two engines share a template, will that techTransfer automatically happen, or will that need to be defined either in the Template creation or Template usage?

That one module, the TestFlightCore module, is still defined specific for each part, and the rest is inherited from the template.  So you would need to define the `techTransfer` on a per engine basis in the "template usage".  That said it is an optional field so if you want to quickly knock out engines, you can skip that property and that given engine just won't have any tech transfer.

**Comment by jwvanderbeck** [comment]
Is this still a plan? I see that the code I Wrote is still sitting as a PR and not merged in.  If we still want to go down this route I can merge it in.  If the plan has changed and this is being handled in another way by the new RO CFG parser, then I can scrap it.

**Comment by NathanKell** [comment]
Ah, I forgot about this when I wrote the MM code. I think that safely supercedes this. Sorry.

**Comment by jwvanderbeck** [comment]
No worries.  I'll close the PR then.
