### ISSUE TITLE
RO engine configurations that have changed name

### ISSUE THREAD

**Issue by MartinNFuller** [KSP-RO/TestFlight#99]
I see you have already fixed the Aerobee configuration names XASR-1 and AJ10-27 to match RO.  That is the only one I have seen in-game, but I found the following in RO_Engines.cfg which do not match any configurations in cfg files for RO 10.5.0:
AJ10-104D : now RO has AJ10-118D and AJ10-118E
LR-89-NA-3
LR-105-NA-5
LR-87-3
LR-87-5
LR-87-7
LR-87-9
LR-87-11
LR-87-11A
RL10A-4-1-2 : appears as RL10A-4-1/2

**Comment by jwvanderbeck** [comment]
This is an old issue and many updates have been done to the configs since then.

If anyone is encountering similar issues please open a **new** issue.
